id = "quo"
name = "Quo Language Support"
version = "0.0.2"
schema_version = 1
authors = ["Vlad Krupinskii <vladkrupinskii@gmail.com>"]
description = "Syntax highlighting for Quo language"
repository = "https://github.com/quo-lang/quo"
grammar = "quo"

[grammars.quo]
repository = "https://github.com/quo-lang/tree-sitter-quo"
rev = "0c31a1b4c28af8489b2553221f1dc8d14df23b78"
