id = "quo"
name = "Quo Language Support"
version = "0.0.2"
schema_version = 1
authors = ["Vlad Krupinskii <vladkrupinskii@gmail.com>"]
description = "Syntax highlighting for Quo language"
repository = "https://github.com/quo-lang/quo"
grammar = "quo"

[grammars.quo]
repository = "https://github.com/quo-lang/tree-sitter-quo"
rev = "dbb68b8056bc29ced1f0664eeeeb4db559fec3cc"
