name: Build Quo CLI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Compile Quo CLI
        run: ./build.sh -b release

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: quo
          prerelease: true
          make_latest: false
