name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Compile Quo CLI
        run: ./build.sh --dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: build/quo-*
          tag_name: ${{ github.ref_name }}
