name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Compile Quo CLI
        run: ./build.sh test
